version: "3.8"

services:
  runejs_game_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/usr/src/app/data
      - ./cache:/usr/src/app/cache
      - ./config:/usr/src/app/config
    ports:
      - "43594:43594"

networks:
  default:
    name: runejs_network
