version: "3.8"

services:
  runejs_game_server:
    image: node:16
    container_name: runejs_game_server
    ports:
      - "43594:43594"
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start

networks:
  default:
    name: runejs_network
