export default [
  {
    "id": 91,
    "name": "Guam potion (unf)",
    "levelRequired": 3,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Guam leaf": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Guam potion.",
    "value": 3,
    "highAlch": 1,
    "lowAlch": 1,
    "weight": 0.056,
    "exchange": 90,
    "buyLimit": 10000,
    "dailyVolume": 418962
  },
  {
    "id": 93,
    "name": "Marrentill potion (unf)",
    "levelRequired": 5,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Marrentill": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Marrentill potion.",
    "value": 5,
    "highAlch": 3,
    "lowAlch": 2,
    "weight": 0.056,
    "exchange": 72,
    "buyLimit": 10000,
    "dailyVolume": 38646
  },
  {
    "id": 95,
    "name": "Tarromin potion (unf)",
    "levelRequired": 12,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Tarromin": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Tarromin potion.",
    "value": 11,
    "highAlch": 6,
    "lowAlch": 4,
    "weight": 0.056,
    "exchange": 213,
    "buyLimit": 10000,
    "dailyVolume": 150866
  },
  {
    "id": 97,
    "name": "Harralander potion (unf)",
    "levelRequired": 22,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Harralander": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Harralander potion.",
    "value": 20,
    "highAlch": 12,
    "lowAlch": 8,
    "weight": 0.056,
    "exchange": 808,
    "buyLimit": 10000,
    "dailyVolume": 196298
  },
  {
    "id": 99,
    "name": "Ranarr potion (unf)",
    "levelRequired": 30,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Ranarr weed": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Ranarr potion.",
    "value": 25,
    "highAlch": 15,
    "lowAlch": 10,
    "weight": 0.056,
    "exchange": 7634,
    "buyLimit": 10000,
    "dailyVolume": 1055870
  },
  {
    "id": 3002,
    "name": "Toadflax potion (unf)",
    "levelRequired": 34,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Vial of water": 1,
      "Toadflax": 1
    },
    "hadReleased": true,
    "released": "27 July 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Toadflax potion.",
    "value": 48,
    "highAlch": 28,
    "lowAlch": 19,
    "weight": 0.056,
    "exchange": 2704,
    "buyLimit": 10000,
    "dailyVolume": 892972
  },
  {
    "id": 101,
    "name": "Irit potion (unf)",
    "levelRequired": 45,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Irit leaf": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Irit potion.",
    "value": 40,
    "highAlch": 24,
    "lowAlch": 16,
    "weight": 0.056,
    "exchange": 861,
    "buyLimit": 10000,
    "dailyVolume": 812062
  },
  {
    "id": 103,
    "name": "Avantoe potion (unf)",
    "levelRequired": 50,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Avantoe": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Avantoe potion.",
    "value": 48,
    "highAlch": 28,
    "lowAlch": 19,
    "weight": 0.056,
    "exchange": 2038,
    "buyLimit": 10000,
    "dailyVolume": 744107
  },
  {
    "id": 105,
    "name": "Kwuarm potion (unf)",
    "levelRequired": 55,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Kwuarm": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Kwuarm potion.",
    "value": 54,
    "highAlch": 32,
    "lowAlch": 21,
    "weight": 0.056,
    "exchange": 1789,
    "buyLimit": 10000,
    "dailyVolume": 494791
  },
  {
    "id": 3004,
    "name": "Snapdragon potion (unf)",
    "levelRequired": 63,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Snapdragon": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 July 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Snapdragon potion.",
    "value": 59,
    "highAlch": 35,
    "lowAlch": 23,
    "weight": 0.056,
    "exchange": 10199,
    "buyLimit": 10000,
    "dailyVolume": 789639
  },
  {
    "id": 107,
    "name": "Cadantine potion (unf)",
    "levelRequired": 66,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Vial of water": 1,
      "Cadantine": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Cadantine potion.",
    "value": 65,
    "highAlch": 39,
    "lowAlch": 26,
    "weight": 0.056,
    "exchange": 2109,
    "buyLimit": 10000,
    "dailyVolume": 390774
  },
  {
    "id": 2483,
    "name": "Lantadyme potion (unf)",
    "levelRequired": 69,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Lantadyme": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "29 March 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Lantadyme potion.",
    "value": 68,
    "highAlch": 40,
    "lowAlch": 27,
    "weight": 0.056,
    "exchange": 1681,
    "buyLimit": 10000,
    "dailyVolume": 811961
  },
  {
    "id": 109,
    "name": "Dwarf weed potion (unf)",
    "levelRequired": 72,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Dwarf weed": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Dwarf Weed potion.",
    "value": 70,
    "highAlch": 42,
    "lowAlch": 28,
    "weight": 0.056,
    "exchange": 1543,
    "buyLimit": 10000,
    "dailyVolume": 671290
  },
  {
    "id": 111,
    "name": "Torstol potion (unf)",
    "levelRequired": 78,
    "boostable": true,
    "xpGain": 0,
    "ticks": 1,
    "materials": {
      "Torstol": 1,
      "Vial of water": 1
    },
    "hadReleased": true,
    "released": "12 December 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "I need another ingredient to finish this Torstol potion.",
    "value": 25,
    "highAlch": 15,
    "lowAlch": 10,
    "weight": 0.056,
    "exchange": 8333,
    "buyLimit": 10000,
    "dailyVolume": 9460
  },
  {
    "id": 5936,
    "name": "Weapon poison+ (unf)",
    "levelRequired": 73,
    "boostable": true,
    "xpGain": 0,
    "ticks": 2,
    "materials": {
      "Coconut milk": 1,
      "Cactus spine": 1
    },
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "A vial of coconut milk and Cactus spine.",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.035
  },
  {
    "id": 5939,
    "name": "Weapon poison++ (unf)",
    "levelRequired": 82,
    "boostable": true,
    "xpGain": 0,
    "ticks": 2,
    "materials": {
      "Coconut milk": 1,
      "Cave nightshade": 1
    },
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "A vial of coconut milk and Deadly Nightshade.",
    "value": 14,
    "highAlch": 8,
    "lowAlch": 5,
    "weight": 0.035
  },
  {
    "id": 3410,
    "name": "Serum 207 (3)",
    "levelRequired": 15,
    "boostable": true,
    "xpGain": 50,
    "ticks": 0,
    "materials": {
      "Tarromin potion (unf)": 1,
      "Ashes": 1
    },
    "hadReleased": true,
    "released": "18 October 2004 (Update)",
    "members": true,
    "questItem": "Shades of Mort'ton",
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "3 doses serum 207 as described in Herbi Flax's diary.",
    "value": 13,
    "highAlch": 7,
    "lowAlch": 5,
    "weight": 0.03,
    "exchange": 6,
    "buyLimit": 2000,
    "dailyVolume": 32734
  },
  {
    "id": 2460,
    "name": "Assorted flowers",
    "nameId": "Assorted flowers",
    "hadReleased": true,
    "released": "29 March 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": true,
    "stackable": false,
    "noteable": true,
    "options": "Wield",
    "destroy": "Drop",
    "examine": "A posy of flowers.",
    "value": 100,
    "highAlch": 60,
    "lowAlch": 40,
    "weight": 0.028,
    "exchange": 284,
    "buyLimit": 150,
    "dailyVolume": 636,
    "-100": 100,
    "otherBonuses": "Slot",
    "-10": 0,
    "attackSpeed": "Range"
  },
  {
    "id": 121,
    "name": "Attack potion(3)",
    "levelRequired": 3,
    "boostable": false,
    "xpGain": 25,
    "ticks": 2,
    "materials": {
      "Guam potion (unf)": 1,
      "Eye of newt": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Attack potion.",
    "value": 12,
    "highAlch": 7,
    "lowAlch": 4,
    "weight": 0.03,
    "respawnTime": 10060,
    "exchange": 4,
    "buyLimit": 2000,
    "dailyVolume": 129617
  },
  {
    "id": 227,
    "name": "Vial of water",
    "ticks": 1,
    "materials": {
      "Vial": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "A glass vial containing water.",
    "value": 2,
    "highAlch": 1,
    "lowAlch": 0,
    "weight": 0.02,
    "exchange": 5,
    "buyLimit": 13000,
    "dailyVolume": 9211704
  },
  {
    "id": 249,
    "name": "Guam leaf",
    "levelRequired": 3,
    "boostable": true,
    "xpGain": 2.5,
    "ticks": 0,
    "materials": {
      "Grimy guam leaf": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A bitter green herb.",
    "value": 3,
    "highAlch": 1,
    "lowAlch": 1,
    "weight": 0.007,
    "exchange": 30,
    "buyLimit": 13000,
    "dailyVolume": 291443
  },
  {
    "id": 221,
    "name": "Eye of newt",
    "nameId": "Eye of newt",
    "hadReleased": true,
    "released": "6 April 2001 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "It seems to be looking at me.",
    "value": 3,
    "highAlch": 1,
    "lowAlch": 1,
    "weight": 0.007,
    "exchange": 4,
    "buyLimit": 13000,
    "dailyVolume": 6087052
  },
  {
    "id": 175,
    "name": "Antipoison(3)",
    "levelRequired": 5,
    "boostable": true,
    "xpGain": 37.5,
    "ticks": 2,
    "materials": {
      "Marrentill potion (unf)": 1,
      "Unicorn horn dust": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of antipoison potion.",
    "value": 288,
    "highAlch": 172,
    "lowAlch": 115,
    "weight": 0.03,
    "exchange": 107,
    "buyLimit": 2000,
    "dailyVolume": 11888
  },
  {
    "id": 251,
    "name": "Marrentill",
    "levelRequired": 1,
    "boostable": true,
    "xpGain": 3.8,
    "ticks": 0,
    "materials": {
      "Grimy marrentill": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A herb used in poison cures.",
    "value": 5,
    "highAlch": 3,
    "lowAlch": 2,
    "weight": 0.007,
    "exchange": 33,
    "buyLimit": 13000,
    "dailyVolume": 494886,
    "firemakingXP": 0,
    "facility": "Burners",
    "type": "Other",
    "requiredTool": "Tinderbox"
  },
  {
    "id": 235,
    "name": "Unicorn horn dust",
    "ticks": 0,
    "materials": {
      "Unicorn horn": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "Finely ground horn of Unicorn.",
    "value": 20,
    "highAlch": 12,
    "lowAlch": 8,
    "weight": 0.007,
    "exchange": 236,
    "buyLimit": 13000,
    "dailyVolume": 122170
  },
  {
    "id": 4844,
    "name": "Relicym's balm(3)",
    "levelRequired": 8,
    "boostable": true,
    "xpGain": 40,
    "ticks": 0,
    "materials": {
      "Unfinished potion (Rogue's Purse)": 1,
      "Snake weed": 1
    },
    "hadReleased": true,
    "released": "17 May 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Relicym's balm, which helps cure disease.",
    "value": 200,
    "highAlch": 120,
    "lowAlch": 80,
    "weight": 0.03,
    "exchange": 454,
    "buyLimit": 2000,
    "dailyVolume": 138
  },
  {
    "id": 1534,
    "name": "Rogue's purse",
    "levelRequired": 3,
    "boostable": false,
    "xpGain": 2.5,
    "ticks": 0,
    "materials": {
      "Grimy rogue's purse": 1
    },
    "hadReleased": true,
    "released": "23 October 2002 (Update)",
    "members": true,
    "questItem": "Jungle Potion",
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "destroy": "Drop",
    "examine": "This herb is Rogue's Purse.",
    "value": 5,
    "highAlch": 3,
    "lowAlch": 2,
    "weight": 0.007
  },
  {
    "id": 1526,
    "name": "Snake weed",
    "levelRequired": 3,
    "boostable": false,
    "xpGain": 2.5,
    "ticks": 0,
    "materials": {
      "Grimy snake weed": 1
    },
    "hadReleased": true,
    "released": "23 October 2002 (Update)",
    "members": true,
    "questItem": "Jungle Potion, Legends' Quest",
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "destroy": "Drop",
    "examine": "This herb is Snake Weed.",
    "value": 5,
    "highAlch": 3,
    "lowAlch": 2,
    "weight": 0.007
  },
  {
    "id": 115,
    "name": "Strength potion(3)",
    "levelRequired": 12,
    "boostable": true,
    "xpGain": 50,
    "ticks": 2,
    "materials": {
      "Tarromin potion (unf)": 1,
      "Limpwurt root": 1
    },
    "hadReleased": true,
    "released": "5 February 2001 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Strength potion.",
    "value": 13,
    "highAlch": 7,
    "lowAlch": 5,
    "weight": 0.03,
    "exchange": 191,
    "buyLimit": 2000,
    "dailyVolume": 48767
  },
  {
    "id": 253,
    "name": "Tarromin",
    "levelRequired": 11,
    "boostable": true,
    "xpGain": 5,
    "ticks": 0,
    "materials": {
      "Grimy tarromin": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A useful herb.",
    "value": 11,
    "highAlch": 6,
    "lowAlch": 4,
    "weight": 0.007,
    "exchange": 158,
    "buyLimit": 13000,
    "dailyVolume": 386536
  },
  {
    "id": 225,
    "name": "Limpwurt root",
    "nameId": "Limpwurt root",
    "hadReleased": true,
    "released": "5 February 2001 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "The root of a limpwurt plant.",
    "value": 7,
    "highAlch": 4,
    "lowAlch": 2,
    "weight": 0.007,
    "exchange": 715,
    "buyLimit": 13000,
    "dailyVolume": 762281
  },
  {
    "id": 592,
    "name": "Ashes",
    "nameId": "Ashes",
    "hadReleased": true,
    "released": "4 January 2001 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A heap of ashes.",
    "value": 2,
    "highAlch": 1,
    "lowAlch": 0,
    "weight": 0.056,
    "respawnTime": 10060,
    "exchange": 49,
    "buyLimit": 13000,
    "dailyVolume": 132293
  },
  {
    "id": 4423,
    "name": "Guthix rest(1)",
    "levelRequired": 18,
    "boostable": true,
    "xpGain": 15.5,
    "ticks": 0,
    "materials": {
      "Herb tea mix": 1,
      "Marrentill": 1
    },
    "hadReleased": true,
    "released": "28 February 2005 (Update)",
    "members": true,
    "questItem": "One Small Favour",
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "A cup of Guthix Rest.",
    "value": 50,
    "highAlch": 30,
    "lowAlch": 20,
    "weight": 0.05,
    "exchange": 466,
    "buyLimit": 2000,
    "dailyVolume": 299
  },
  {
    "id": 4460,
    "name": "Cup of hot water",
    "ticks": 0,
    "materials": {
      "Bowl of hot water": 1,
      "Empty cup": 1
    },
    "hadReleased": true,
    "released": "28 February 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "It's hot!",
    "value": 10,
    "highAlch": 6,
    "lowAlch": 4,
    "weight": 0.05,
    "exchange": 336,
    "buyLimit": 13000,
    "dailyVolume": 1707
  },
  {
    "id": 255,
    "name": "Harralander",
    "levelRequired": 20,
    "boostable": true,
    "xpGain": 6.3,
    "ticks": 0,
    "materials": {
      "Grimy harralander": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A useful herb.",
    "value": 20,
    "highAlch": 12,
    "lowAlch": 8,
    "weight": 0.007,
    "exchange": 677,
    "buyLimit": 13000,
    "dailyVolume": 176907
  },
  {
    "id": 6472,
    "name": "Compost potion(3)",
    "levelRequired": 22,
    "boostable": true,
    "xpGain": 60,
    "ticks": 2,
    "materials": {
      "Harralander potion (unf)": 1,
      "Volcanic ash": 1
    },
    "hadReleased": true,
    "released": "30 August 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "Pour this on compost to turn it into super-compost.",
    "value": 90,
    "highAlch": 54,
    "lowAlch": 36,
    "weight": 0.03,
    "exchange": 54,
    "buyLimit": 50,
    "dailyVolume": 5744
  },
  {
    "id": 127,
    "name": "Restore potion(3)",
    "levelRequired": 22,
    "boostable": true,
    "xpGain": 62.5,
    "ticks": 2,
    "materials": {
      "Harralander potion (unf)": 1,
      "Red spiders' eggs": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of restore potion.",
    "value": 88,
    "highAlch": 52,
    "lowAlch": 35,
    "weight": 0.03,
    "exchange": 40,
    "buyLimit": 2000,
    "dailyVolume": 5624
  },
  {
    "id": 223,
    "name": "Red spiders' eggs",
    "nameId": "Red spiders' eggs",
    "hadReleased": true,
    "released": "5 February 2001 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "Ewww!",
    "value": 7,
    "highAlch": 4,
    "lowAlch": 2,
    "weight": 0.007,
    "respawnTime": 10060,
    "exchange": 413,
    "buyLimit": 13000,
    "dailyVolume": 1621942
  },
  {
    "id": 7662,
    "name": "Guthix balance(3)",
    "levelRequired": 22,
    "boostable": true,
    "xpGain": 25,
    "ticks": 0,
    "materials": {
      "undefined": null
    },
    "hadReleased": true,
    "released": "22 March 2006 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "A potion of harralander, red spiders eggs, garlic and silver dust.",
    "value": 200,
    "highAlch": 120,
    "lowAlch": 80,
    "weight": 0.035,
    "exchange": 125,
    "buyLimit": 2000,
    "dailyVolume": 8
  },
  {
    "id": 1550,
    "name": "Garlic",
    "nameId": "Garlic",
    "hadReleased": true,
    "released": "28 January 2001 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "edible": "no",
    "destroy": "Drop",
    "examine": "A clove of garlic.",
    "value": 3,
    "highAlch": 1,
    "lowAlch": 1,
    "weight": 0.028,
    "respawnTime": 5030,
    "exchange": 47,
    "buyLimit": 11000,
    "dailyVolume": 39295
  },
  {
    "id": 7650,
    "name": "Silver dust",
    "ticks": 4,
    "materials": {
      "Silver bar": 1
    },
    "hadReleased": true,
    "released": "22 March 2006 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "It's ground up silver.",
    "value": 200,
    "highAlch": 120,
    "lowAlch": 80,
    "weight": 0.15,
    "exchange": 120,
    "buyLimit": 13000,
    "dailyVolume": 132
  },
  {
    "id": 1582,
    "name": "Blamish oil",
    "levelRequired": 25,
    "boostable": true,
    "xpGain": 80,
    "ticks": 2,
    "materials": {
      "Blamish snail slime": 1,
      "Harralander potion (unf)": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": "Heroes' Quest",
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "options": "Drink",
    "destroy": "Drop",
    "examine": "Made from the finest snail slime.",
    "value": 10,
    "highAlch": 6,
    "lowAlch": 4,
    "weight": 0.025
  },
  {
    "id": 1581,
    "name": "Blamish snail slime",
    "ticks": 0,
    "materials": {
      "Sample bottle": 1,
      "Thin snail": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": "Heroes' Quest",
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "destroy": "Drop",
    "examine": "Yuck.",
    "value": 5,
    "highAlch": 3,
    "lowAlch": 2,
    "weight": 0.025
  },
  {
    "id": 3010,
    "name": "Energy potion(3)",
    "levelRequired": 26,
    "boostable": true,
    "xpGain": 67.5,
    "ticks": 2,
    "materials": {
      "Harralander potion (unf)": 1,
      "Chocolate dust": 1
    },
    "hadReleased": true,
    "released": "1 September 2004 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of energy potion.",
    "value": 110,
    "highAlch": 66,
    "lowAlch": 44,
    "weight": 0.03,
    "exchange": 296,
    "buyLimit": 2000,
    "dailyVolume": 71023
  },
  {
    "id": 1975,
    "name": "Chocolate dust",
    "ticks": 0,
    "materials": {
      "Chocolate bar": 1
    },
    "hadReleased": true,
    "released": "27 August 2002 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "It's ground up chocolate.",
    "value": 2,
    "highAlch": 1,
    "lowAlch": 0,
    "weight": 0.15,
    "exchange": 28,
    "buyLimit": 13000,
    "dailyVolume": 220594
  },
  {
    "id": 133,
    "name": "Defence potion(3)",
    "levelRequired": 30,
    "boostable": true,
    "xpGain": 75,
    "ticks": 2,
    "materials": {
      "Ranarr potion (unf)": 1,
      "White berries": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Defence potion.",
    "value": 120,
    "highAlch": 72,
    "lowAlch": 48,
    "weight": 0.03,
    "exchange": 230,
    "buyLimit": 2000,
    "dailyVolume": 1062
  },
  {
    "id": 257,
    "name": "Ranarr weed",
    "levelRequired": 25,
    "boostable": true,
    "xpGain": 7.5,
    "ticks": 0,
    "materials": {
      "Grimy ranarr weed": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A useful herb.",
    "value": 25,
    "highAlch": 15,
    "lowAlch": 10,
    "weight": 0.007,
    "exchange": 7327,
    "buyLimit": 11000,
    "dailyVolume": 497979
  },
  {
    "id": 239,
    "name": "White berries",
    "nameId": "White berries",
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "Sour berries, used in potions.",
    "value": 10,
    "highAlch": 6,
    "lowAlch": 4,
    "weight": 0.007,
    "respawnTime": 106,
    "exchange": 171,
    "buyLimit": 13000,
    "dailyVolume": 658362
  },
  {
    "id": 3034,
    "name": "Agility potion(3)",
    "levelRequired": 34,
    "boostable": true,
    "xpGain": 80,
    "ticks": 2,
    "materials": {
      "Toadflax potion (unf)": 1,
      "Toad's legs": 1
    },
    "hadReleased": true,
    "released": "27 July 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Agility potion.",
    "value": 150,
    "highAlch": 90,
    "lowAlch": 60,
    "weight": 0.03,
    "exchange": 141,
    "buyLimit": 2000,
    "dailyVolume": 1268
  },
  {
    "id": 2998,
    "name": "Toadflax",
    "levelRequired": 30,
    "boostable": true,
    "xpGain": 8,
    "ticks": 0,
    "materials": {
      "Grimy toadflax": 1
    },
    "hadReleased": true,
    "released": "27 July 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A useful herb.",
    "value": 48,
    "highAlch": 28,
    "lowAlch": 19,
    "weight": 0.007,
    "exchange": 2504,
    "buyLimit": 13000,
    "dailyVolume": 578415
  },
  {
    "id": 2152,
    "name": "Toad's legs",
    "ticks": 0,
    "materials": {
      "Swamp toad (item)": 1
    },
    "hadReleased": true,
    "released": "12 December 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "edible": true,
    "options": "Eat",
    "destroy": "Drop",
    "examine": "They're a gnome delicacy apparently.",
    "value": 2,
    "highAlch": 1,
    "lowAlch": 0,
    "weight": 0.15,
    "exchange": 717,
    "buyLimit": 13000,
    "dailyVolume": 3051
  },
  {
    "id": 9741,
    "name": "Combat potion(3)",
    "levelRequired": 36,
    "boostable": true,
    "xpGain": 84,
    "ticks": 2,
    "materials": {
      "Harralander potion (unf)": 1,
      "Goat horn dust": 1
    },
    "hadReleased": true,
    "released": "18 October 2006 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of combat potion.",
    "value": 160,
    "highAlch": 96,
    "lowAlch": 64,
    "weight": 0.03,
    "exchange": 359,
    "buyLimit": 2000,
    "dailyVolume": 46051
  },
  {
    "id": 9736,
    "name": "Goat horn dust",
    "ticks": 0,
    "materials": {
      "Desert goat horn": 1
    },
    "hadReleased": true,
    "released": "18 October 2006 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "Finely ground desert goat horn.",
    "value": 12,
    "highAlch": 7,
    "lowAlch": 4,
    "weight": 0.453,
    "exchange": 93,
    "buyLimit": 13000,
    "dailyVolume": 64435
  },
  {
    "id": 139,
    "name": "Prayer potion(3)",
    "levelRequired": 38,
    "boostable": true,
    "xpGain": 87.5,
    "ticks": 2,
    "materials": {
      "Ranarr potion (unf)": 1,
      "Snape grass": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Prayer restore potion.",
    "value": 152,
    "highAlch": 91,
    "lowAlch": 60,
    "weight": 0.03,
    "exchange": 7349,
    "buyLimit": 2000,
    "dailyVolume": 408847
  },
  {
    "id": 231,
    "name": "Snape grass",
    "nameId": "Snape grass",
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "Strange spiky grass.",
    "value": 10,
    "highAlch": 6,
    "lowAlch": 4,
    "weight": 0.007,
    "respawnTime": 3018,
    "exchange": 278,
    "buyLimit": 13000,
    "dailyVolume": 1693998
  },
  {
    "id": 145,
    "name": "Super attack(3)",
    "levelRequired": 45,
    "boostable": true,
    "xpGain": 100,
    "ticks": 2,
    "materials": {
      "Irit potion (unf)": 1,
      "Eye of newt": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of super Attack potion.",
    "value": 180,
    "highAlch": 108,
    "lowAlch": 72,
    "weight": 0.03,
    "exchange": 151,
    "buyLimit": 2000,
    "dailyVolume": 293209
  },
  {
    "id": 259,
    "name": "Irit leaf",
    "levelRequired": 40,
    "boostable": true,
    "xpGain": 8.8,
    "ticks": 0,
    "materials": {
      "Grimy irit leaf": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A useful herb.",
    "value": 40,
    "highAlch": 24,
    "lowAlch": 16,
    "weight": 0.007,
    "exchange": 714,
    "buyLimit": 13000,
    "dailyVolume": 372989
  },
  {
    "id": 181,
    "name": "Superantipoison(3)",
    "levelRequired": 48,
    "boostable": true,
    "xpGain": 106.3,
    "ticks": 2,
    "materials": {
      "Irit potion (unf)": 1,
      "Unicorn horn dust": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of super antipoison potion.",
    "value": 288,
    "highAlch": 172,
    "lowAlch": 115,
    "weight": 0.03,
    "respawnTime": 10060,
    "exchange": 137,
    "buyLimit": 2000,
    "dailyVolume": 20138
  },
  {
    "id": 151,
    "name": "Fishing potion(3)",
    "levelRequired": 50,
    "boostable": true,
    "xpGain": 112.5,
    "ticks": 2,
    "materials": {
      "Avantoe potion (unf)": 1,
      "Snape grass": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Fishing potion.",
    "value": 200,
    "highAlch": 120,
    "lowAlch": 80,
    "weight": 0.03,
    "exchange": 107,
    "buyLimit": 2000,
    "dailyVolume": 4202
  },
  {
    "id": 261,
    "name": "Avantoe",
    "levelRequired": 48,
    "boostable": true,
    "xpGain": 10,
    "ticks": 0,
    "materials": {
      "Grimy avantoe": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A useful herb.",
    "value": 48,
    "highAlch": 28,
    "lowAlch": 19,
    "weight": 0.007,
    "exchange": 1826,
    "buyLimit": 13000,
    "dailyVolume": 341211
  },
  {
    "id": 3018,
    "name": "Super energy(3)",
    "levelRequired": 52,
    "boostable": true,
    "xpGain": 117.5,
    "ticks": 2,
    "materials": {
      "Avantoe potion (unf)": 1,
      "Mort myre fungus": 1
    },
    "hadReleased": true,
    "released": "1 September 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of super energy potion.",
    "value": 230,
    "highAlch": 138,
    "lowAlch": 92,
    "weight": 0.03,
    "exchange": 1476,
    "buyLimit": 2000,
    "dailyVolume": 346935
  },
  {
    "id": 2970,
    "name": "Mort myre fungus",
    "nameId": "Mort myre fungus",
    "hadReleased": true,
    "released": "13 July 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A mushroom from the swamps of Mort Myre.",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.01,
    "exchange": 490,
    "buyLimit": 13000,
    "dailyVolume": 715221
  },
  {
    "id": 157,
    "name": "Super strength(3)",
    "levelRequired": 55,
    "boostable": true,
    "xpGain": 125,
    "ticks": 2,
    "materials": {
      "Kwuarm potion (unf)": 1,
      "Limpwurt root": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of super Strength potion.",
    "value": 220,
    "highAlch": 132,
    "lowAlch": 88,
    "weight": 0.03,
    "exchange": 1506,
    "buyLimit": 2000,
    "dailyVolume": 208576
  },
  {
    "id": 263,
    "name": "Kwuarm",
    "levelRequired": 54,
    "boostable": true,
    "xpGain": 11.3,
    "ticks": 0,
    "materials": {
      "Grimy kwuarm": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A powerful herb.",
    "value": 54,
    "highAlch": 32,
    "lowAlch": 21,
    "weight": 0.007,
    "exchange": 1578,
    "buyLimit": 13000,
    "dailyVolume": 272744
  },
  {
    "id": 9022,
    "name": "Magic essence(3)",
    "levelRequired": 57,
    "boostable": true,
    "xpGain": 130,
    "ticks": 2,
    "materials": {
      "Magic essence (unf)": 1,
      "Gorak claw powder": 1
    },
    "hadReleased": true,
    "released": "11 July 2006 (Update)",
    "members": true,
    "questItem": "Fairytale II - Cure a Queen",
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of magic essence potion.",
    "value": 230,
    "highAlch": 138,
    "lowAlch": 92,
    "weight": 0.03
  },
  {
    "id": 9017,
    "name": "Star flower",
    "nameId": "Star flower",
    "hadReleased": true,
    "released": "11 July 2006 (Update)",
    "members": true,
    "questItem": "Fairy Tale II - Cure a Queen",
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "destroy": "Drop",
    "examine": "A rare flower with magical properties.",
    "value": 75,
    "highAlch": 45,
    "lowAlch": 30,
    "weight": 0.001
  },
  {
    "id": 9018,
    "name": "Gorak claw powder",
    "ticks": 0,
    "materials": {
      "Gorak claws": 1
    },
    "hadReleased": true,
    "released": "11 July 2006 (Update)",
    "members": true,
    "questItem": "Fairy Tale II - Cure a Queen",
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "destroy": "Drop",
    "examine": "Ground-down Gorak claws.",
    "value": 150,
    "highAlch": 90,
    "lowAlch": 60,
    "weight": 0.001
  },
  {
    "id": 187,
    "name": "Weapon poison",
    "levelRequired": 60,
    "boostable": true,
    "xpGain": 137.5,
    "ticks": 2,
    "materials": {
      "Kwuarm potion (unf)": 1,
      "Dragon scale dust": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "For use on daggers and projectiles.",
    "value": 144,
    "highAlch": 86,
    "lowAlch": 57,
    "weight": 0.025,
    "exchange": 399,
    "buyLimit": 2000,
    "dailyVolume": 13821
  },
  {
    "id": 241,
    "name": "Dragon scale dust",
    "ticks": 0,
    "materials": {
      "Blue dragon scale": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "Finely ground scale of Dragon.",
    "value": 52,
    "highAlch": 31,
    "lowAlch": 20,
    "weight": 0.007,
    "exchange": 156,
    "buyLimit": 13000,
    "dailyVolume": 379194
  },
  {
    "id": 3026,
    "name": "Super restore(3)",
    "levelRequired": 63,
    "boostable": true,
    "xpGain": 142.5,
    "ticks": 2,
    "materials": {
      "Snapdragon potion (unf)": 1,
      "Red spiders' eggs": 1
    },
    "hadReleased": true,
    "released": "27 July 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of super restore potion.",
    "value": 240,
    "highAlch": 144,
    "lowAlch": 96,
    "weight": 0.03,
    "exchange": 9304,
    "buyLimit": 2000,
    "dailyVolume": 221259
  },
  {
    "id": 3000,
    "name": "Snapdragon",
    "levelRequired": 59,
    "boostable": true,
    "xpGain": 11.8,
    "ticks": 0,
    "materials": {
      "Grimy snapdragon": 1
    },
    "hadReleased": true,
    "released": "27 July 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A powerful herb.",
    "value": 59,
    "highAlch": 35,
    "lowAlch": 23,
    "weight": 0.007,
    "exchange": 9820,
    "buyLimit": 11000,
    "dailyVolume": 388402
  },
  {
    "id": 163,
    "name": "Super defence(3)",
    "levelRequired": 66,
    "boostable": true,
    "xpGain": 150,
    "ticks": 2,
    "materials": {
      "Cadantine potion (unf)": 1,
      "White berries": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of super Defence potion.",
    "value": 264,
    "highAlch": 158,
    "lowAlch": 105,
    "weight": 0.03,
    "exchange": 616,
    "buyLimit": 2000,
    "dailyVolume": 178877
  },
  {
    "id": 265,
    "name": "Cadantine",
    "levelRequired": 65,
    "boostable": true,
    "xpGain": 12.5,
    "ticks": 0,
    "materials": {
      "Grimy cadantine": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A powerful herb.",
    "value": 65,
    "highAlch": 39,
    "lowAlch": 26,
    "weight": 0.007,
    "exchange": 1926,
    "buyLimit": 11000,
    "dailyVolume": 407652
  },
  {
    "id": 5945,
    "name": "Antidote+(3)",
    "levelRequired": 68,
    "boostable": true,
    "xpGain": 155,
    "ticks": 2,
    "materials": {
      "Coconut milk": 1,
      "Toadflax": 1,
      "Yew roots": 1
    },
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of extra strong antipoison potion.",
    "value": 288,
    "highAlch": 172,
    "lowAlch": 115,
    "weight": 0.035,
    "exchange": 1820,
    "buyLimit": 4000,
    "dailyVolume": 23
  },
  {
    "id": 5935,
    "name": "Coconut milk",
    "ticks": 0,
    "materials": {
      "Vial": 1,
      "Half coconut": 1
    },
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "A vial filled with coconut milk",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.035,
    "exchange": 1263,
    "buyLimit": 11000,
    "dailyVolume": 4215
  },
  {
    "id": 6049,
    "name": "Yew roots",
    "nameId": "Yew roots",
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "The roots of the Yew tree.",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.001,
    "exchange": 154,
    "buyLimit": 11000,
    "dailyVolume": 1574
  },
  {
    "id": 2454,
    "name": "Antifire potion(3)",
    "levelRequired": 69,
    "boostable": true,
    "xpGain": 157.5,
    "ticks": 2,
    "materials": {
      "Lantadyme potion (unf)": 1,
      "Dragon scale dust": 1
    },
    "hadReleased": true,
    "released": "29 March 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of anti-firebreath potion.",
    "value": 264,
    "highAlch": 158,
    "lowAlch": 105,
    "weight": 0.03,
    "exchange": 195,
    "buyLimit": 2000,
    "dailyVolume": 99224
  },
  {
    "id": 2481,
    "name": "Lantadyme",
    "levelRequired": 67,
    "boostable": true,
    "xpGain": 13.1,
    "ticks": 0,
    "materials": {
      "Grimy lantadyme": 1
    },
    "hadReleased": true,
    "released": "29 March 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A powerful herb.",
    "value": 68,
    "highAlch": 40,
    "lowAlch": 27,
    "weight": 0.007,
    "exchange": 1470,
    "buyLimit": 11000,
    "dailyVolume": 467753
  },
  {
    "id": 169,
    "name": "Ranging potion(3)",
    "levelRequired": 72,
    "boostable": true,
    "xpGain": 162.5,
    "ticks": 2,
    "materials": {
      "Dwarf weed potion (unf)": 1,
      "Wine of zamorak": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of ranging potion.",
    "value": 288,
    "highAlch": 172,
    "lowAlch": 115,
    "weight": 0.03,
    "exchange": 276,
    "buyLimit": 2000,
    "dailyVolume": 160869
  },
  {
    "id": 267,
    "name": "Dwarf weed",
    "levelRequired": 70,
    "boostable": true,
    "xpGain": 13.8,
    "ticks": 0,
    "materials": {
      "Grimy dwarf weed": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A powerful herb.",
    "value": 70,
    "highAlch": 42,
    "lowAlch": 28,
    "weight": 0.007,
    "exchange": 1335,
    "buyLimit": 11000,
    "dailyVolume": 603122
  },
  {
    "id": 245,
    "name": "Wine of zamorak",
    "levelRequired": 65,
    "boostable": true,
    "xpGain": 200,
    "ticks": 20,
    "materials": {
      "Zamorak's grapes": 1,
      "Jug of water": 1
    },
    "hadReleased": true,
    "released": "27 February 2002 (Update)",
    "members": false,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "An evil wine for an evil god.",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.085,
    "respawnTime": 5030,
    "exchange": 703,
    "buyLimit": 11000,
    "dailyVolume": 2342484
  },
  {
    "id": 5937,
    "name": "Weapon poison(+)",
    "levelRequired": 73,
    "boostable": true,
    "xpGain": 165,
    "ticks": 2,
    "materials": {
      "Coconut milk": 1,
      "Cactus spine": 1,
      "Red spiders' eggs": 1
    },
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "A vial of extra strong weapon poison, for spears and daggers.",
    "value": 288,
    "highAlch": 172,
    "lowAlch": 115,
    "weight": 0.035,
    "exchange": 855,
    "buyLimit": 2000,
    "dailyVolume": 1136
  },
  {
    "id": 6016,
    "name": "Cactus spine",
    "nameId": "Cactus spine",
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "None (?)",
    "destroy": "Drop",
    "examine": "Don't prick yourself with this.",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.028,
    "exchange": 1703,
    "buyLimit": 11000,
    "dailyVolume": 368543
  },
  {
    "id": 3042,
    "name": "Magic potion(3)",
    "levelRequired": 76,
    "boostable": true,
    "xpGain": 172.5,
    "ticks": 2,
    "materials": {
      "Lantadyme potion (unf)": 1,
      "Potato cactus": 1
    },
    "hadReleased": true,
    "released": "7 September 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Magic potion.",
    "value": 250,
    "highAlch": 150,
    "lowAlch": 100,
    "weight": 0.03,
    "exchange": 48,
    "buyLimit": 2000,
    "dailyVolume": 126823
  },
  {
    "id": 3138,
    "name": "Potato cactus",
    "nameId": "Potato cactus",
    "hadReleased": true,
    "released": "7 September 2004 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "How am I supposed to eat that?!",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.5,
    "respawnTime": 10060,
    "exchange": 654,
    "buyLimit": 11000,
    "dailyVolume": 662121
  },
  {
    "id": 189,
    "name": "Zamorak brew(3)",
    "levelRequired": 78,
    "boostable": true,
    "xpGain": 175,
    "ticks": 2,
    "materials": {
      "Torstol potion (unf)": 1,
      "Jangerberries": 1
    },
    "hadReleased": true,
    "released": "12 December 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Zamorak brew.",
    "value": 175,
    "highAlch": 105,
    "lowAlch": 70,
    "weight": 0.03,
    "exchange": 1352,
    "buyLimit": 2000,
    "dailyVolume": 2230
  },
  {
    "id": 269,
    "name": "Torstol",
    "levelRequired": 75,
    "boostable": true,
    "xpGain": 15,
    "ticks": 0,
    "materials": {
      "Grimy torstol": 1
    },
    "hadReleased": true,
    "released": "12 December 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A powerful herb.",
    "value": 75,
    "highAlch": 45,
    "lowAlch": 30,
    "weight": 0.007,
    "exchange": 7783,
    "buyLimit": 11000,
    "dailyVolume": 446135
  },
  {
    "id": 247,
    "name": "Jangerberries",
    "nameId": "Jangerberries",
    "hadReleased": true,
    "released": "12 December 2002 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "edible": true,
    "options": "Eat",
    "destroy": "Drop",
    "examine": "They don't look very ripe.",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.007,
    "respawnTime": 3018,
    "exchange": 240,
    "buyLimit": 13000,
    "dailyVolume": 44055
  },
  {
    "id": 5954,
    "name": "Antidote++(3)",
    "levelRequired": 79,
    "boostable": true,
    "xpGain": 177.5,
    "ticks": 2,
    "materials": {
      "Coconut milk": 1,
      "Irit leaf": 1,
      "Magic roots": 1
    },
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of super strong antipoison potion.",
    "value": 288,
    "highAlch": 172,
    "lowAlch": 115,
    "weight": 0.035,
    "exchange": 1214,
    "buyLimit": 4000,
    "dailyVolume": 2648
  },
  {
    "id": 6051,
    "name": "Magic roots",
    "nameId": "Magic roots",
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "The roots of the Magic tree.",
    "value": 1,
    "highAlch": 0,
    "lowAlch": 0,
    "weight": 0.001,
    "exchange": 1847,
    "buyLimit": 11000,
    "dailyVolume": 1116
  },
  {
    "id": 6687,
    "name": "Saradomin brew(3)",
    "levelRequired": 81,
    "boostable": true,
    "xpGain": 180,
    "ticks": 2,
    "materials": {
      "Toadflax potion (unf)": 1,
      "Crushed nest": 1
    },
    "hadReleased": true,
    "released": "24 October 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Drink, Empty",
    "destroy": "Drop",
    "examine": "3 doses of Saradomin brew.",
    "value": 175,
    "highAlch": 105,
    "lowAlch": 70,
    "weight": 0.03,
    "exchange": 3580,
    "buyLimit": 2000,
    "dailyVolume": 269641
  },
  {
    "id": 6693,
    "name": "Crushed nest",
    "ticks": 0,
    "materials": {
      "Bird nest (empty)": 1
    },
    "hadReleased": true,
    "released": "24 October 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "A crushed bird's nest.",
    "value": 200,
    "highAlch": 120,
    "lowAlch": 80,
    "weight": 0.002,
    "exchange": 3673,
    "buyLimit": 11000,
    "dailyVolume": 924141
  },
  {
    "id": 5940,
    "name": "Weapon poison(++)",
    "levelRequired": 82,
    "boostable": true,
    "xpGain": 190,
    "ticks": 2,
    "materials": {
      "Weapon poison++ (unf)": 1,
      "Poison ivy berries": 1
    },
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "options": "Empty",
    "destroy": "Drop",
    "examine": "A vial of super strong weapon poison, for spears and daggers.",
    "value": 432,
    "highAlch": 259,
    "lowAlch": 172,
    "weight": 0.035,
    "exchange": 3469,
    "buyLimit": 2000,
    "dailyVolume": 11802
  },
  {
    "id": 2398,
    "name": "Cave nightshade",
    "nameId": "Cave nightshade",
    "hadReleased": true,
    "released": "7 May 2003 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": false,
    "equipable": false,
    "stackable": false,
    "options": "Eat",
    "destroy": "Drop",
    "examine": "Deadly.",
    "value": 30,
    "highAlch": 18,
    "lowAlch": 12,
    "weight": 0.015,
    "respawnTime": 10060
  },
  {
    "id": 6018,
    "name": "Poison ivy berries",
    "nameId": "Poison ivy berries",
    "hadReleased": true,
    "released": "11 July 2005 (Update)",
    "members": true,
    "questItem": false,
    "tradeable": true,
    "equipable": false,
    "stackable": false,
    "noteable": true,
    "destroy": "Drop",
    "examine": "They look sweet and juicy, but only a fool would eat them.",
    "value": 65,
    "highAlch": 39,
    "lowAlch": 26,
    "weight": 0.007,
    "exchange": 65,
    "buyLimit": 11000,
    "dailyVolume": 183817
  }
];