name: Lint & Build Project

on:
    pull_request:
        branches: [ master, develop, feature/** ]
    push:
        branches: [ master, develop ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Setup Node
                uses: actions/setup-node@v1
                with:
                    node-version: '20.x'

            -   name: Install Node Modules
                run: npm i

            -   name: Run Linter
                run: npm run lint

            -   name: Run Typecheck
                run: npm run typecheck

            -   name: Build Project
                run: npm run build
